#!/usr/bin/env bash
# rathole noise-encrypted reverse-tunnel client bootstrap (one-shot)
#
# Usage (run as root on the internal host you want to expose):
#   curl -fsSL https://raw.githubusercontent.com/erwanjun/rathole-bootstrap/main/setup_rathole_client.sh \
#     | sudo bash -s -- \
#         -s 120.26.178.114:2333 \
#         -t <DEFAULT_TOKEN> \
#         -p <NOISE_REMOTE_PUBLIC_KEY> \
#         -n <service-name> \
#         [-l 127.0.0.1:22]
#
# Long forms also work: --server / --token / --pubkey / --service / --local / --version
#
# Server side (already running on the cloud host) must have a matching
# [server.services.<name>] block bound to a public TCP port.

set -euo pipefail

SERVER=""
TOKEN=""
PUBKEY=""
SERVICE=""
LOCAL="127.0.0.1:22"
RATHOLE_VERSION="v0.5.0"

while [[ $# -gt 0 ]]; do
  case "$1" in
    -s|--server)  SERVER="$2";  shift 2;;
    -t|--token)   TOKEN="$2";   shift 2;;
    -p|--pubkey)  PUBKEY="$2";  shift 2;;
    -n|--service) SERVICE="$2"; shift 2;;
    -l|--local)   LOCAL="$2";   shift 2;;
    --version) RATHOLE_VERSION="$2"; shift 2;;
    -h|--help)
      sed -n '2,18p' "$0" 2>/dev/null || cat <<'EOF'
Usage: setup_rathole_client.sh -s IP:PORT -t TOKEN -p PUBKEY -n NAME [-l 127.0.0.1:22]
EOF
      exit 0;;
    *) echo "Unknown arg: $1" >&2; exit 1;;
  esac
done

[[ -z "$SERVER" || -z "$TOKEN" || -z "$PUBKEY" || -z "$SERVICE" ]] && {
  echo "Missing required args. -s / -t / -p / -n are mandatory." >&2
  exit 1
}
[[ $EUID -ne 0 ]] && { echo "Must run as root (sudo)." >&2; exit 1; }

ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  ASSET="rathole-x86_64-unknown-linux-gnu.zip" ;;
  aarch64) ASSET="rathole-aarch64-unknown-linux-musl.zip" ;;
  armv7l)  ASSET="rathole-armv7-unknown-linux-musleabihf.zip" ;;
  *) echo "Unsupported arch: $ARCH" >&2; exit 1 ;;
esac

echo "=== [1/5] install rathole $RATHOLE_VERSION ($ARCH -> $ASSET) ==="
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

URL="https://github.com/rathole-org/rathole/releases/download/${RATHOLE_VERSION}/${ASSET}"
MIRRORS=(
  "$URL"
  "https://ghps.cc/$URL"
  "https://gh-proxy.com/$URL"
  "https://mirror.ghproxy.com/$URL"
)
ok=0
for u in "${MIRRORS[@]}"; do
  echo "-> try: $u"
  if curl -fsSL --connect-timeout 10 --max-time 120 -o "$TMPDIR/r.zip" "$u"; then
    ok=1; break
  fi
done
[[ $ok -eq 1 ]] || { echo "download failed from all mirrors" >&2; exit 1; }

if ! command -v unzip >/dev/null; then
  if command -v apt-get >/dev/null; then apt-get update -qq && apt-get install -y -qq unzip
  elif command -v yum     >/dev/null; then yum install -y -q unzip
  elif command -v dnf     >/dev/null; then dnf install -y -q unzip
  else echo "Please install 'unzip' manually." >&2; exit 1
  fi
fi

unzip -q -o "$TMPDIR/r.zip" -d "$TMPDIR"
install -m 755 "$TMPDIR/rathole" /usr/bin/rathole
echo "  installed: $(/usr/bin/rathole --version 2>&1 | head -1)"

echo "=== [2/5] write systemd unit ==="
cat >/etc/systemd/system/rathole@.service <<'EOF'
[Unit]
Description=rathole (%i)
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
Restart=on-failure
RestartSec=5s
LimitNOFILE=1048576
Environment=RUST_LOG=info
ExecStart=/usr/bin/rathole /etc/rathole/%i.toml
ExecReload=/bin/kill -HUP $MAINPID

[Install]
WantedBy=multi-user.target
EOF

echo "=== [3/5] write /etc/rathole/client.toml ==="
mkdir -p /etc/rathole
chmod 700 /etc/rathole
cat >/etc/rathole/client.toml <<EOF
# Generated by setup_rathole_client.sh
[client]
remote_addr = "${SERVER}"
default_token = "${TOKEN}"
heartbeat_timeout = 40

[client.transport]
type = "noise"
[client.transport.noise]
remote_public_key = "${PUBKEY}"

[client.services.${SERVICE}]
type = "tcp"
local_addr = "${LOCAL}"
EOF
chmod 600 /etc/rathole/client.toml

echo "=== [4/5] enable + start rathole@client ==="
systemctl daemon-reload
systemctl enable --now rathole@client
sleep 3

echo "=== [5/5] verify ==="
if systemctl is-active --quiet rathole@client; then
  echo "  rathole@client is active"
else
  echo "  rathole@client failed to start. Recent logs:" >&2
  journalctl -u rathole@client -n 30 --no-pager >&2 || true
  exit 1
fi

SERVER_HOST="${SERVER%%:*}"
SERVER_PORT="${SERVER##*:}"
ESTAB=$(ss -tnp 2>/dev/null | grep -E "${SERVER_HOST}:${SERVER_PORT}\b" | head -3 || true)
if [[ -n "$ESTAB" ]]; then
  echo "  control channel established:"
  echo "$ESTAB" | sed 's/^/    /'
else
  echo "  no ESTAB seen yet; check 'journalctl -u rathole@client -f'" >&2
fi

cat <<EOF

================================================================
DONE.
  service:        ${SERVICE}
  forwards:       <cloud server>:<published-port>  ->  $(hostname):${LOCAL}
  status:         systemctl status rathole@client
  logs (live):    journalctl -u rathole@client -f
  uninstall:      systemctl disable --now rathole@client && rm -f /etc/rathole/client.toml /usr/bin/rathole

Don't forget to open the published port in the cloud security group,
and add a Host entry in your local ~/.ssh/config.
================================================================
EOF
